# Generated by Django 2.2.7 on 2020-01-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('type_of_movie', models.CharField(max_length=40)),
                ('release_date', models.DateTimeField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('cast_name', models.CharField(max_length=40)),
                ('producer_name', models.CharField(max_length=20)),
                ('director_name', models.CharField(max_length=20)),
            ],
        ),
    ]
